---
title: "Crohn's Dashboard"
output: 
 flexdashboard::flex_dashboard:
    orientation: columns
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(plotly)
library(ggplot2)
library(readr)
library(prophet)
library(extrafont)
library(leaflet)
library(car)
library(ggmap)
library(lubridate)
library(DT)
library(stringr)
```


Column {data-width=600}
-----------------------------------------------------------------------

### Prophet Predictions

```{r, include=FALSE}
poop <- read_csv('https://docs.google.com/spreadsheets/d/1Ow1OTP3QfyQyi1K2jeyqjv5eg_AzqF36Tn3sn5NSQQw/pub?gid=444517334&single=true&output=csv')

poop$time <- format(as.POSIXct(strptime(poop$Timestamp,"%m/%d/%Y %H:%M:%S",tz="")) ,format = "%H:%M:%S")
poop$ds  <- format(as.POSIXct(strptime(poop$Timestamp,"%m/%d/%Y %H:%M",tz="")) ,format = "%Y-%m-%d")

poop$time <- format(as.POSIXct(strptime(poop$Timestamp,"%m/%d/%Y %H:%M:%S",tz="")) ,format = "%H:%M:%S")
poop$time <- as.POSIXct(poop$time, "%m/%d/%Y %H:%M:%S",tz="")

poop$t2 <- as.POSIXct(poop$Timestamp, "%m/%d/%Y %H:%M:%S",tz="")
poop$hour <- hour(poop$t2)
#poop$hour <- Recode(poop$hour, "0:6=1; 7:10=2; 11:14=3; 15:19=4; 20:22=5; 23:24=1")

day <- poop %>% group_by(ds) %>% summarise(y = n())

m <- prophet(day)


future <- make_future_dataframe(m, periods = 15)
forecast <- predict(m, future)
plot(m, forecast)
prophet_plot_components(m, forecast)


fb <-ggplot(forecast, aes(ds)) + geom_ribbon(aes(ymin = forecast$yhat_lower, ymax = forecast$yhat_upper), fill = "#3b5998") +
  geom_line(aes(y = yhat), size =1, color = "#dfe3ee") +
  geom_point(aes(y =yhat), color = "#dfe3ee") +  
  xlab("Date") + ylab("Projected Number") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) +
  theme(panel.background = element_rect(fill = "gray77")) +
  ggtitle("Using Facebook's Prophet to make Predictions")
```

```{r}
ggplotly(fb)
```

### Mapping the Movements

```{r}
poop$locate <- Recode(poop$`Where are You?`, "'Church' = '1600 Salem Road, Mount Vernon IL'; 
                                      'EIU' = '600 Lincoln Avenue, Charleston IL';
                                      'Fairview Heights' = 'Fairview Heights, IL';
                                      'FBC' = '1600 Salem Road, Mount Vernon IL';
                                      'Galleria' = 'Galleria St. Louis, MO';
                                      'Home' = '1803 Isabella Avenue, Mt Vernon IL';
                                      'Okawville' = 'Okawville, IL'")

mapdata <- poop %>% group_by(locate) %>% summarise(count = n())        

coords <- geocode(mapdata$locate)

mapdata <- cbind(mapdata, coords)

pop<-paste0("<b>Address</b>: ", mapdata$locate, "<br>",
            "<b>Count</b>: ", mapdata$count)

leaflet() %>% 
  addProviderTiles(providers$Stamen.TonerHybrid) %>% 
  addCircleMarkers(lng = mapdata$lon, lat = mapdata$lat, radius = mapdata$count, popup = pop)

```


Column {.tabset .tabset-fade data-width=400}
-----------------------------------------------------------------------

### Movements by Day
```{r, fig.keep='none'}
poop$time <- format(as.POSIXct(strptime(poop$Timestamp,"%m/%d/%Y %H:%M:%S",tz="")) ,format = "%H:%M:%S")
poop$day  <- format(as.POSIXct(strptime(poop$Timestamp,"%m/%d/%Y %H:%M",tz="")) ,format = "%Y-%m-%d")

plotdata <- poop %>% group_by(day) %>% summarise(y = n())

plotdata$day <- as.Date(plotdata$day)

alldates = seq(min(plotdata$day), max(plotdata$day), 1)

dates0 = alldates[!(alldates %in% plotdata$day)]
data0 = data.frame(day = dates0, y = NA_real_)

data = rbind(plotdata, data0)
data = data[order(data$day),]

data[is.na(data)] <- 0

#title <- "Daily Counts"
#mean <- paste("Mean =", round(mean(data$y), digits = 2))

byday <- ggplot(data, aes(x=day, y=y)) + geom_bar(aes(fill = ..y..), stat = "identity") +  
  theme(axis.text.x = element_text(angle = 90)) + 
  xlab("Date") +ylab("Number of Movements") +
  ggtitle("Daily Counts") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + 
  scale_fill_gradient(low = "burlywood", high = "burlywood4") + 
  theme(legend.position="none") + geom_hline(yintercept = mean(data$y),  linetype = "longdash") 

ggplotly(byday)


```

### Quality by Day 

```{r}
qualitydata <- poop %>% group_by(day) %>% summarise(mean = mean(`How Bad Is It?`))
qualitydata$mean <- 9 -qualitydata$mean

quality <- ggplot(qualitydata, aes(x=day, y=mean)) + geom_bar(aes(fill = ..y..), stat = "identity") +  
  theme(axis.text.x = element_text(angle = 90)) + 
  xlab("Date") +ylab("Higher Values = Worse") +
  ggtitle("How Bad Is It?") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + 
  scale_fill_gradient(low = "gray87", high = "firebrick1") + 
  theme(legend.position="none") + geom_vline(xintercept = 40.5,  linetype = "longdash")

ggplotly(quality)

```

### Time of the Day
```{r}

byhour <- poop %>% group_by(hour) %>% summarise(y =n()) %>% mutate(pct = y/sum(y))

hourplot <- ggplot(byhour, aes(x=hour, y=pct*100)) + geom_bar(aes(fill=pct), stat="identity") +  
  xlab("Time of Day - 24 Hour Format") +ylab("Percent of Movements") +
  ggtitle("Which Time of the Day is Worst?") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + 
  scale_fill_gradient(low = "deepskyblue4", high = "deepskyblue") + 
  theme(legend.position="none")  +
  scale_x_continuous(breaks = round(seq(min(byhour$hour), max(byhour$hour), by = 1),1))

ggplotly(hourplot)
```

### Day of the Week
```{r}
data$daysweek <- strftime(data$day,'%A')

daysweek <- data %>% group_by(daysweek) %>% summarise(mean = mean(y)) 

daysweek$daysweek <- factor(daysweek$daysweek, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))


dayweekplot <- ggplot(daysweek, aes(x=daysweek, y=mean)) + geom_bar(aes(fill=mean), stat="identity") +  
  xlab("Day of the Week") +ylab("Average Movements that Day") +
  ggtitle("Which Day of the Week is Worst?") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + 
  scale_fill_gradient(low = "darkorchid4", high = "darkorchid1") + 
  theme(legend.position="none")  

ggplotly(dayweekplot)
```

### Grouped by Week
```{r}

data$weeks <- format(data$day, format="%Y-%U")
data$wk <- str_sub(data$weeks, start= -2)


#poop$wkcount <- (poop$weeks - min(poop$weeks))/dweeks(1)
#poop$wkcount <- round(poop$wkcount, 0)

weekly <- data %>% group_by(wk) %>% summarise(mean = mean(y)) 


weeklyplot <- ggplot(weekly, aes(x=wk, y=mean)) + geom_bar(aes(fill=mean), stat="identity") +  
  xlab("Week of the Year") +ylab("Average Movements Per Day of Each Week") +
  ggtitle("Is the Remicade Wearing off?") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + 
  scale_fill_gradient(low = "darkorange4", high = "darkorange1") + 
  theme(legend.position="none")  

ggplotly(weeklyplot)
```

